services:
  # 1. Backend service
  backend:
    image: nginxdemos/hello
    networks:
      - envoy_network

  # 2. Envoy Proxy
  envoy:
    image: envoyproxy/envoy:v1.28-latest
    ports:
      - "8080:8080"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    networks:
      - envoy_network
    depends_on:
      - authz-service

  # 3. Service Authz (của Người B)
  authz-service:
    build: ./authz
    networks:
      - envoy_network

# ĐỊNH NGHĨA NETWORK CHUNG
networks:
  envoy_network:
    driver: bridge